import React, { useState, useEffect } from "react";
import Box from '@mui/material/Box';
import { TextField, Button, Grid } from "@mui/material";
import Head from 'next/head';
import { useRouter } from 'next/router';
import Cookies from 'js-cookie';
import Link from 'next/link';
import bgImage from '../lib/assets/play_bg.png';

export default function Home() {

  return (
    <div>
      <Head>
        <title>Immersive Tech Companion App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box style={{backgroundImage: `url(${bgImage.src})`, backgroundRepeat: "no-repeat", backgroundPosition: "center", backgroundAttachment: "scroll"}}>
          <Box sx={{height: "60vh"}}></Box>
          <h1 style={{ margin: "0 auto auto 5%", fontSize: "45px" }}>Hyper-</h1>
          <h1 style={{ margin: "0 auto auto 5%", fontSize: "45px" }}>Immersive VR with Friends</h1>
          <Link href="/booking">
            <Button variant="contained" sx={{ bgcolor: "gray", margin: "5% auto auto 5%" }}>Book an Experience</Button>
          </Link>
        </Box>
      </main>
    </div>
  )
}
